### ISSUE TITLE
What's the entry point for this lib?

### ISSUE THREAD

**Issue by jeremybullock** [ideasman42/curve-fit-nd#4]
Hi Campbell, 
I hope you are doing well.  

I'm trying to figure out how to use this library with a set of 2d points.

Could you please let me know where I should start with this.

Thanks,
Jeremy Bullock (turtletooth)

**Comment by ideasman42** [comment]
Check https://github.com/ideasman42/curve-fit-nd/blob/master/c_python_ext/curve_fit_nd_ext.c this calls a `curve_fit_*` function that does the fitting.

**Comment by jeremybullock** [comment]
Thank you.  With your help and some example code from Blender, I was able to figure it out.  Thank you for making this library.  It's working nicely!
